# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 10:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=4)),
                ('seats_first_class', models.IntegerField()),
                ('seats_business', models.IntegerField()),
                ('seats_economy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=8)),
                ('estimated_time_departure', models.DateTimeField()),
                ('estimated_time_arrival', models.DateTimeField()),
                ('location_departure', models.CharField(max_length=3)),
                ('location_arrival', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=40)),
                ('airlines', models.ManyToManyField(to='flylo.Airline')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Airplane')),
            ],
            options={
                'ordering': ['estimated_time_departure', 'location_arrival'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('e', 'Economy'), ('b', 'Business'), ('f', 'First Class')], max_length=1)),
                ('seat', models.CharField(blank=True, max_length=4, null=True)),
                ('price', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('checkin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Airline')),
                ('client', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='flylo.Client')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Flight')),
            ],
        ),
    ]
