# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['estimated_time_departure', 'location_arrival']},
        ),
    ]
