# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0002_flight_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='price',
            new_name='base_price',
        ),
    ]
