# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0002_auto_20170426_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=4)),
                ('seats_first_class', models.IntegerField()),
                ('seats_business', models.IntegerField()),
                ('seats_economy', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flylo.Airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flylo.Airplane'),
        ),
    ]
