# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0003_auto_20170427_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airplane',
        ),
    ]
