# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0004_auto_20170512_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['estimated_time_departure']},
        ),
    ]
