# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0005_auto_20170427_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.AddField(
            model_name='flight',
            name='airlines',
            field=models.ManyToManyField(to='flylo.Airline'),
        ),
    ]
