# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-18 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0006_auto_20170518_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
