# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0007_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('e', 'Economy'), ('b', 'Bussiness'), ('f', 'First Class')], max_length=1)),
                ('seat', models.CharField(max_length=4)),
                ('price', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('checkin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Airline')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flylo.Flight')),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
