# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-04 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylo', '0009_auto_20170504_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
